name: TOC Consistency

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  toc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Generate TOC
        run: |
          python tools/toc_generator.py --root . --output docs/toc.md

      - name: Validate TOC
        run: |
          python tools/toc_validate.py --root . --toc docs/toc.md

      - name: Fail if TOC changes are needed
        run: |
          if [ -n "$(git status --porcelain docs/toc.md)" ]; then
            echo "TOC is outdated. Please commit updated docs/toc.md"
            git --no-pager diff -- docs/toc.md | cat
            exit 1
          fi

